const constants = {
    FETCH_ALL: 'FETCH_ALL_GROUPS',
    FETCH: 'GROUP_FETCH',
    DELETE: 'GROUP_DELETE',
    EDIT: 'GROUP_EDIT',
    CREATE: 'GROUP_CREATE',
    INIT: 'GROUP_COMPONENT_INIT'
};

export default constants;

// export const constants = {
//     FETCH_ALL_REQUEST: 'FETCH_ALL_GROUPS_REQUEST',
//     FETCH_ALL_SUCCESS: 'FETCH_ALL_GROUPS_SUCCESS',
//     FETCH_ALL_FAILURE: 'FETCH_ALL_GROUPS_FAILURE',

//     DELETE_REQUEST: 'GROUP_DELETE_REQUEST',
//     DELETE_SUCCESS: 'GROUP_DELETE_SUCCESS',
//     DELETE_FAILURE: 'GROUP_DELETE_FAILURE',

//     ENABLE_REQUEST: 'GROUP_ENABLE_REQUEST',
//     ENABLE_SUCCESS: 'GROUP_ENABLE_SUCCESS',
//     ENABLE_FAILURE: 'GROUP_ENABLE_FAILURE',

//     EDIT_REQUEST: 'GROUP_EDIT_REQUEST',
//     EDIT_SUCCESS: 'GROUP_EDIT_SUCCESS',
//     EDIT_FAILURE: 'GROUP_EDIT_FAILURE',

//     CREATE_REQUEST: 'GROUP_CREATE_REQUEST',
//     CREATE_SUCCESS: 'GROUP_CREATE_SUCCESS',
//     CREATE_FAILURE: 'GROUP_CREATE_FAILURE'
// };
