const constants = {
    FETCH_ALL: 'USERS_FETCH_ALL',
    FETCH: 'USER_FETCH',
    DELETE: 'USER_DELETE',
    ENABLE: 'USER_ENABLE',
    EDIT: 'USER_EDIT',
    CREATE: 'USER_CREATE'
};

export default constants;

// export const constants = {
//     FETCH_ALL_REQUEST: 'FETCH_ALL_USERS_REQUEST',
//     FETCH_ALL_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
//     FETCH_ALL_FAILURE: 'FETCH_ALL_USERS_FAILURE',

//     DELETE_REQUEST: 'USER_DELETE_REQUEST',
//     DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
//     DELETE_FAILURE: 'USER_DELETE_FAILURE',

//     ENABLE_REQUEST: 'USER_ENABLE_REQUEST',
//     ENABLE_SUCCESS: 'USER_ENABLE_SUCCESS',
//     ENABLE_FAILURE: 'USER_ENABLE_FAILURE',

//     EDIT_REQUEST: 'USER_EDIT_REQUEST',
//     EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
//     EDIT_FAILURE: 'USER_EDIT_FAILURE',

//     CREATE_REQUEST: 'USER_CREATE_REQUEST',
//     CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
//     CREATE_FAILURE: 'USER_CREATE_FAILURE',

//     ADD_TO_GROUP_REQUEST: 'USER_ADD_TO_GROUP_REQUEST',
//     ADD_TO_GROUP_SUCCESS: 'USER_ADD_TO_GROUP_SUCCESS',
//     ADD_TO_GROUP_FAILURE: 'USER_ADD_TO_GROUP_FAILURE',

//     REMOVE_FROM_GROUP_REQUEST: 'USER_REMOVE_FROM_GROUP_REQUEST',
//     REMOVE_FROM_GROUP_SUCCESS: 'USER_REMOVE_FROM_GROUP_SUCCESS',
//     REMOVE_FROM_GROUP_FAILURE: 'USER_REMOVE_FROM_GROUP_FAILURE'
// };
