const constants = {
    FETCH_ALL: 'APPLICATION_FETCH_ALL',
    FETCH: 'APPLICATION_FETCH',
    DELETE: 'APPLICATION_DELETE',
    EDIT: 'APPLICATION_EDIT',
    CREATE: 'APPLICATION_CREATE'
};

export default constants;

// export const constants = {
//     FETCH_ALL_REQUEST: 'FETCH_ALL_APPLICATION_REQUEST',
//     FETCH_ALL_SUCCESS: 'FETCH_ALL_APPLICATION_SUCCESS',
//     FETCH_ALL_FAILURE: 'FETCH_ALL_APPLICATION_FAILURE',

//     DELETE_REQUEST: 'APPLICATION_DELETE_REQUEST',
//     DELETE_SUCCESS: 'APPLICATION_DELETE_SUCCESS',
//     DELETE_FAILURE: 'APPLICATION_DELETE_FAILURE',

//     ENABLE_REQUEST: 'APPLICATION_ENABLE_REQUEST',
//     ENABLE_SUCCESS: 'APPLICATION_ENABLE_SUCCESS',
//     ENABLE_FAILURE: 'APPLICATION_ENABLE_FAILURE',

//     EDIT_REQUEST: 'APPLICATION_EDIT_REQUEST',
//     EDIT_SUCCESS: 'APPLICATION_EDIT_SUCCESS',
//     EDIT_FAILURE: 'APPLICATION_EDIT_FAILURE',

//     CREATE_REQUEST: 'APPLICATION_CREATE_REQUEST',
//     CREATE_SUCCESS: 'APPLICATION_CREATE_SUCCESS',
//     CREATE_FAILURE: 'APPLICATION_CREATE_FAILURE',

//     ADD_ALLOWED_GROUP_REQUEST: 'APPLICATION_ADD_ALLOWED_GROUP_REQUEST',
//     ADD_ALLOWED_GROUP_SUCCESS: 'APPLICATION_ADD_ALLOWED_GROUP_SUCCESS',
//     ADD_ALLOWED_GROUP_FAILURE: 'APPLICATION_ADD_ALLOWED_GROUP_FAILURE'
// };
